from __future__ import annotations

import argparse
import os
from pathlib import Path
from typing import Sequence

from .auth import generate_api_key


def build_env_file(*, salt: str, sha256: str) -> str:
    return "\n".join(
        [
            "# Generated by python -m cloud_api.setup_gateway",
            "# Secrets stay blank until supplied. Inventory-only and future variables remain commented.",
            "",
            "# -----------------------------------------------------------------------------",
            "# Active gateway runtime settings (read by the current code)",
            "# -----------------------------------------------------------------------------",
            "# The plaintext admin bearer token is intentionally not stored here.",
            "# setup_gateway prints it once; store it in a password manager.",
            f"VISUAL_AGENT_CLOUD_API_KEY_SHA256={sha256}",
            f"VISUAL_AGENT_CLOUD_API_KEY_SALT={salt}",
            "VISUAL_AGENT_CLOUD_ORG=pacer-gateway",
            "VISUAL_AGENT_CLOUD_USER=admin",
            "VISUAL_AGENT_CLOUD_RUN_PROFILE=dry-run",
            "VISUAL_AGENT_CLOUD_ENABLE_TOKEN_ISSUER=0",
            "PACER_GATEWAY_DB=/data/gateway.db",
            "VISUAL_AGENT_WORKSPACE_ROOT=/data/workspace",
            "VISUAL_AGENT_CLOUD_AUDIT_LOG=/data/cloud-api-audit.jsonl",
            "PACER_GATEWAY_MAX_REQUEST_BYTES=10485760",
            "",
            "# Upstream API keys. The variable name must exactly match secret_env in the UI.",
            "# Leave unused entries empty; non-empty placeholders are treated as configured keys.",
            "# Use only API accounts whose terms permit this gateway workload and resale model.",
            "PACER_UPSTREAM_PRIMARY_KEY=",
            "PACER_UPSTREAM_BACKUP_KEY=",
            "",
            "# -----------------------------------------------------------------------------",
            "# Account and registration inventory (current gateway code does not read these)",
            "# -----------------------------------------------------------------------------",
            "# Keep passwords, MFA seeds, recovery codes and private keys in a password manager.",
            "# PACER_ADMIN_LOGIN_EMAIL=",
            "# PACER_BILLING_EMAIL=",
            "# PACER_SECURITY_ALERT_EMAIL=",
            "# PACER_SUPPORT_EMAIL=",
            "# PACER_LEGAL_ENTITY_NAME=",
            "# PACER_BILLING_ENTITY_NAME=",
            "# PACER_TAX_ID=",
            "# PACER_UPSTREAM_PRIMARY_SIGNUP_EMAIL=",
            "# PACER_UPSTREAM_PRIMARY_ACCOUNT_ID=",
            "# PACER_UPSTREAM_PRIMARY_BASE_URL=",
            "# PACER_UPSTREAM_BACKUP_SIGNUP_EMAIL=",
            "# PACER_UPSTREAM_BACKUP_ACCOUNT_ID=",
            "# PACER_UPSTREAM_BACKUP_BASE_URL=",
            "",
            "# -----------------------------------------------------------------------------",
            "# Domain, TLS and deployment inventory (not read by current gateway code)",
            "# -----------------------------------------------------------------------------",
            "# PACER_PUBLIC_DOMAIN=",
            "# PACER_ACME_EMAIL=",
            "# PACER_DOMAIN_REGISTRAR_ACCOUNT_EMAIL=",
            "# PACER_DNS_PROVIDER_ACCOUNT_EMAIL=",
            "# PACER_DNS_API_TOKEN=",
            "# PACER_SERVER_PROVIDER_ACCOUNT_EMAIL=",
            "# PACER_CONTAINER_REGISTRY_USERNAME=",
            "# PACER_CONTAINER_REGISTRY_TOKEN=",
            "# PACER_TLS_CERTIFICATE_PATH=",
            "# PACER_TLS_PRIVATE_KEY_PATH=",
            "# PACER_BACKUP_ENCRYPTION_KEY=",
            "# PACER_SENTRY_DSN=",
            "",
            "# -----------------------------------------------------------------------------",
            "# Optional broader Cloud API services (implemented, not required by gateway Compose)",
            "# -----------------------------------------------------------------------------",
            "# VISUAL_AGENT_R2_BUCKET=",
            "# VISUAL_AGENT_R2_ENDPOINT=",
            "# VISUAL_AGENT_R2_PUBLIC_BASE_URL=",
            "# VISUAL_AGENT_R2_ACCESS_KEY_ID=",
            "# VISUAL_AGENT_R2_SECRET_ACCESS_KEY=",
            "# VISUAL_AGENT_CELERY_BROKER_URL=redis://redis:6379/0",
            "# VISUAL_AGENT_CELERY_RESULT_BACKEND=redis://redis:6379/1",
            "",
            "# -----------------------------------------------------------------------------",
            "# Email notifications (Pacer supports these; gateway Compose does not use them yet)",
            "# -----------------------------------------------------------------------------",
            "# CHECKPOINT_SMTP_HOST=",
            "# CHECKPOINT_SMTP_PORT=587",
            "# CHECKPOINT_SMTP_USERNAME=",
            "# CHECKPOINT_SMTP_PASSWORD=",
            "# CHECKPOINT_NOTIFY_FROM=",
            "# CHECKPOINT_NOTIFY_TO=",
            "",
            "# -----------------------------------------------------------------------------",
            "# FUTURE ONLY: payment automation is not implemented in the current gateway",
            "# Filling these values does not enable checkout, webhooks, refunds or reconciliation.",
            "# -----------------------------------------------------------------------------",
            "# STRIPE_ACCOUNT_EMAIL=",
            "# STRIPE_SECRET_KEY=",
            "# STRIPE_PUBLISHABLE_KEY=",
            "# STRIPE_WEBHOOK_SECRET=",
            "# WECHAT_PAY_ACCOUNT_EMAIL=",
            "# WECHAT_PAY_MCH_ID=",
            "# WECHAT_PAY_APP_ID=",
            "# WECHAT_PAY_API_V3_KEY=",
            "# WECHAT_PAY_CERT_SERIAL_NO=",
            "# WECHAT_PAY_PRIVATE_KEY_PATH=",
            "# WECHAT_PAY_PLATFORM_CERT_PATH=",
            "# ALIPAY_ACCOUNT_EMAIL=",
            "# ALIPAY_APP_ID=",
            "# ALIPAY_APP_PRIVATE_KEY_PATH=",
            "# ALIPAY_PUBLIC_KEY_PATH=",
            "# ALIPAY_NOTIFY_URL=",
            "",
            "# Customer pacer_sk_* keys are issued in the Gateway UI and must not be added here.",
            "",
        ]
    )


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Initialize a Pacer Gateway environment file."
    )
    parser.add_argument("--env-file", default="cloud_api/.env.gateway")
    parser.add_argument("--force", action="store_true")
    args = parser.parse_args(argv)
    target = Path(args.env_file).expanduser().resolve()
    if target.exists() and not args.force:
        parser.error(f"Refusing to overwrite existing file: {target}")
    key = generate_api_key(prefix="va_cloud_admin")
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(
        build_env_file(salt=key.salt, sha256=key.sha256), encoding="utf-8"
    )
    try:
        os.chmod(target, 0o600)
    except OSError:
        pass
    print(f"Environment file: {target}")
    print(f"Admin bearer token (shown once): {key.token}")
    print("Open /gateway and use this token under Administrator credentials.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
